# Generated by Django 5.1.1 on 2024-10-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoryname', models.CharField(blank=True, max_length=100, null=True)),
                ('Productname', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Mrp', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufactured', models.CharField(blank=True, max_length=100, null=True)),
                ('Productimage1', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('Productimage2', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('Productimage3', models.ImageField(blank=True, null=True, upload_to='product_image')),
            ],
        ),
    ]
